services:
  server:
    build: .
    container_name: webrtc_server
    ports:
      - "8085:8085"
    environment:
      - TZ=Europe/Minsk
    networks:
      - sharednetwork
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/status" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sharednetwork:
    external: true