# Используйте официальный образ Node.js в качестве базового
FROM node:22

# Установите рабочую директорию
WORKDIR /app2

# Скопируйте package.json и yarn.lock в контейнер
COPY package.json yarn.lock ./

# Скопируйте директорию prisma в контейнер
COPY prisma ./prisma

# Установите зависимости
RUN yarn install --frozen-lockfile

# Скопируйте все файлы из корневой директории в контейнер
COPY . .

# Выполните сборку приложения
RUN yarn build

# Установите переменные окружения
ENV NODE_ENV=production

# Запустите приложение
CMD ["yarn", "start"]


## Используйте официальный образ Node.js в качестве базового
#FROM node:22
#WORKDIR /app2
#COPY package.json yarn.lock ./
#COPY prisma ./prisma
#RUN yarn install
#COPY . .
#RUN yarn build
#CMD ["yarn", "start"]